### ISSUE TITLE
Win 7

### ISSUE THREAD

**Issue by harryray33** [zWolfrost/WinContextTweaker#1]
Does this work with Win 7?

Thanks

**Comment by zWolfrost** [comment]
I have only tested it in win10 and win11, but it should work in 7 as well. I will boot up a vm and let you know.

**Comment by harryray33** [comment]
Great, thanks

**Comment by zWolfrost** [comment]
I'm sorry, i've tried everything, but windows 7 won't boot it. Maybe you'll have more luck than me. Remember to install vc-redist and .NET 6.0

**Comment by zWolfrost** [comment]
I just found the issue; basically .NET for windows 7 requires an additional dependency, basically a security update. You can install it [here](https://www.microsoft.com/en-us/download/details.aspx?id=47442), in addition, obviously, to .NET and vc-redist, which you probably already have. For more information about .NET dependencies, you can go to [this ms doc page](https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net60#dependencies)

**Comment by zWolfrost** [comment]
Needless to say, with these requirements, WinContextTweaker on windows 7 does boot up.

![image](https://github.com/zWolfrost/WinContextTweaker/assets/101343066/e6cd1b88-afa8-4419-b59c-8f54252580bb)

Hope this late comment can still help you, have a nice day.

**Comment by harryray33** [comment]
Thanks, I don't think I have 3063858..I tried Googling to see what the update was for, but couldn't find anything specific, just that it was a security up date.

I just want to make sure installing KB3063858 is OK to install, as I got a bit fed up with the MS updates causing problems.

**Comment by zWolfrost** [comment]
Yeah, for that i'm afraid i can't help you. If it makes you feel a little more safe, this security update is listed as a .NET 6.0 dependency for Windows 7 by microsoft themselves [right there](https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net60#additional-deps) (as i said previously). Also, Windows 7 is a quite battle-tested OS, so i suppose that a required dependency for such an important framework (.NET) would be bug-free. In fact, it is not new by any means, it was published in 2015.

**Comment by zWolfrost** [comment]
One more thing, it's not fair to say it's a "windows update", as it's more of a package. I was able to uninstall it in the "Installed Updates" window in the control panel.

![image](https://github.com/zWolfrost/WinContextTweaker/assets/101343066/ce0a3dea-eace-489b-b574-8f9557413672)
