### ISSUE TITLE
Can't add entry to .py extention

### ISSUE THREAD

**Issue by Deuracell** [zWolfrost/WinContextTweaker#2]
Tried to add a Run entry to .py files:
![image](https://github.com/zWolfrost/WinContextTweaker/assets/3322308/cf8c05c0-b68a-45c8-88c5-c87d8aa4d7b1)
But when i click OK no entry is added.
I've tried a few other formats with no issue.

**Comment by zWolfrost** [comment]
Hi, i just fixed this bug in v1.3.0. Basically it would affect file extensions that had no registry entry to begin with. I hope this bug didn't cause you too much of a hassle. Thank you for reporting it and also for your patience.
